[package]
name = "fedra-broker"
version = "0.1.0"
authors = ["Jiayi Hu <jiayi.ghu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.38"
brokerapi = "0.1.0"
env_logger = "0.8.3"
futures = "0.3"
k8s-openapi = { version = "0.10.0", default-features = false, features = ["v1_19"] }
kube = "0.46.0"
kube-runtime = "0.46.0"
log = "0.4.11"
once_cell = "1.5.2"
serde = "1.0.118"
serde_json = "1.0.61"

[patch.crates-io]
brokerapi = { path = "../brokerapi-rs" }
