apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-wasi-rust
data:
  myval: "cool stuff"
  bacon_ipsum.txt: |
    Bacon ipsum dolor amet chuck turducken porchetta, tri-tip spare ribs t-bone ham hock. Meatloaf
    pork belly leberkas, ham beef pig corned beef boudin ground round meatball alcatra jerky.
    Pancetta brisket pastrami, flank pork chop ball tip short loin burgdoggen. Tri-tip kevin
    shoulder cow andouille. Prosciutto chislic cupim, short ribs venison jerky beef ribs ham hock
    short loin fatback. Bresaola meatloaf capicola pancetta, prosciutto chicken landjaeger andouille
    swine kielbasa drumstick cupim tenderloin chuck shank. Flank jowl leberkas turducken ham tongue
    beef ribs shankle meatloaf drumstick pork t-bone frankfurter tri-tip.
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-wasi-rust
spec:
  containers:
    - name: hello-world-wasi-rust
      image: webassembly.azurecr.io/hello-world-wasi-rust:v0.2.0
      env:
        - name: FOO
          value: bar
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONFIG_MAP_VAL
          valueFrom:
            configMapKeyRef:
              key: myval
              name: hello-world-wasi-rust
      volumeMounts:
        - name: storage
          mountPath: /mnt/storage
  volumes:
    - name: storage
      configMap:
        name: hello-world-wasi-rust
  nodeSelector:
    kubernetes.io/arch: "wasm32-wasi"
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoSchedule"
