---

- hosts: master
  gather_facts: no
  become: yes
  tasks:
  - name: Get K3s passwords for the nodes
    command: cat /var/lib/rancher/k3s/server/cred/node-passwd
    register: passwords

  - debug: msg="{{ passwords.stdout.split('\n') }}"
