---
- hosts: node
  gather_facts: no
  become: yes
  tasks:
  - name: Disable services
    service:
      name: krustlet
      state: stopped
      enabled: no

  - name: Remove service files, binaries and data
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - /etc/init.d/krustlet
      - /etc/runlevels/default/krustlet
      - ~{{ ansible_user }}/.krustlet
      - /usr/local/bin/krustlet-wasi
