[package]
name = "coap-lite"
description = """
A lightweight CoAP message manipulation crate, ideal for embedded environments.
"""
version = "0.3.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
repository = "https://github.com/martindisch/coap-lite"
readme = "README.md"
keywords = ["coap"]
categories = ["network-programming", "no-std", "embedded"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]

[features]
default = ["std"]
std = []

[badges]
maintenance = { status = "passively-maintained" }
