[package]
name = "coap-bench"
version = "0.1.0"
authors = ["Jiayi Hu <jiayi.ghu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
coap = "0.9.2"
coap-lite = "0.4.1"
futures = "0.3.14"
tokio = { version = "1.4.0", features = ["full"] }
