[target.thumbv7em-none-eabi]
# runner = "qemu-system-gnuarmeclipse --board STM32F429I-Discovery -d unimp,guest_errors --semihosting-config enable=on target=native --nographic --image"
runner = "probe-run --chip STM32F429ZITX"

rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabi"
