[target.thumbv7em-none-eabi]
# runner = "qemu-system-gnuarmeclipse --board STM32F429I-Discovery -d unimp,guest_errors --semihosting-config enable=on target=native --nographic --image"
runner = "probe-run --chip STM32F429ZITX"

rustflags = [
  "-A", "unstable_name_collisions",
  "-C", "link-arg=-Tlink.x",
  # "-C", "linker=arm-none-eabi-ld",
  # "-C", "link-arg=-lc",
  # "-C", "link-arg=-L/usr/local/opt/gcc-arm-none-eabi/arm-none-eabi/lib/thumb/v7e-m/nofp",
]

[build]
target = "thumbv7em-none-eabi"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
