[package]
name = "fedra-db"
version = "0.1.0"
authors = ["Jiayi Hu <jiayi.ghu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
env_logger = "0.8.3"
futures = "0.3.13"
log = "0.4.14"
warp = "0.3.0"
tokio = { version = "1.2.0", features = ["full"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"
sled = "0.34.6"
