[package]
name = "krustlet-bench"
version = "0.1.0"
authors = ["Jiayi Hu <jiayi.ghu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
env_logger = "0.8.3"
futures = "0.3"
log = "0.4.14"
tokio = { version = "1.2.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "native-tls"] }
native-tls = "0.2.7"
