[package]
name = "fedra-ml"
version = "0.1.0"
authors = ["Jiayi Hu <jiayi.ghu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tract-core = "0.12.5"
tract-onnx = "0.12.5"

[lib]
name = "fedra_ml"
crate-type = ["cdylib"]

[[bin]]
name = "predict"
path = "src/predict.rs"

[profile.release]
lto = true
opt-level = "z"
