[package]
name = "fedra-application"
version = "0.1.0"
authors = ["Jiayi Hu <jiayi.ghu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
env_logger = "0.8.3"
futures = "0.3"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_19"] }
kube = { version = "0.50.1", features = ["derive", "ws"]}
kube-runtime = "0.50.1"
log = "0.4.14"
reqwest = { version = "0.11", features = ["json"] }
schemars = "0.8.0"
serde = "1.0.123"
serde_json = "1.0.63"
tokio = { version = "1.2.0", features = ["full"] }
websocket = "0.26.2"
google-cloud = { git = "https://github.com/jiayihu/google-cloud-rs", features = ["datastore", "datastore-derive"]}
base64 = "0.13.0"
byteorder = "1.4.2"

[features]
default = ["dev"]
dev = []
