[tasks.cross]
command = "cross"
args = ["build", "--target", "aarch64-unknown-linux-gnu", "--release"]

[tasks.docker-build]
command = "docker"
args = [
  "build",
  ".",
  "--tag=eu.gcr.io/fedra-301320/fedra-application:arm64v8",
  "--build-arg",
  "PLATFORM=arm64v8",
  "--build-arg",
  "CROSS_BUILD_TARGET=aarch64-unknown-linux-gnu",
]

[tasks.docker-push]
command = "docker"
args = ["push", "eu.gcr.io/fedra-301320/fedra-application:arm64v8"]

[tasks.deploy]
dependencies = ["cross", "docker-build", "docker-push"]
