apiVersion: v1
kind: Pod
metadata:
  name: add
spec:
  containers:
    - name: add
      image: eu.gcr.io/fedra-301320/add:latest
  nodeSelector:
    kubernetes.io/arch: "wasm32-wasi"
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoSchedule"
